### ISSUE TITLE
Hand tracking seems not to be working.

### ISSUE THREAD

**Issue by TrickPixeltje** [AlcheraInc/Face-Hand-Detection-Unity#3]
Hello,

I have problems with getting hand tracking to work.
I have tried using your demo app to no success, :(.

Hardware:
Samsung s8
Android 9

**Comment by sugang-alchera** [comment]
We are very sorry about your inconvenience. 
I think your Android device won't have a big problem.

Are you saying that you've tested demo app on Playstore and only hand part didn't work?
(Is face sample is OK?)
or Any build problem before running?

**Comment by TrickPixeltje** [comment]
hello,

The hand part doesn't work.
The face part works perfectly fine :)

**Comment by jhoonPark** [comment]
hello.

We tested demo app on Playstore and confirm that hand recognition scene works fine.
I'll be able to help you more about this problem if you can upload the android logcat when your app crashed or gets an error

**Comment by jonalex** [comment]
I've downloaded the demo app and at first I was about to agree with this post, but then realized that the hand needs to be at a certain distance before the CV can detect it as a hand.

Try moving your hand further away from the camera.

Not sure if this is the bug instead.  At some point the camera can clearly see my hand, but it's not until I push it further away that it detects it.

**Comment by sugang-alchera** [comment]
> I've downloaded the demo app and at first I was about to agree with this post, but then realized that the hand needs to be at a certain distance before the CV can detect it as a hand.
> 
> Try moving your hand further away from the camera.
> 
> Not sure if this is the bug instead. At some point the camera can clearly see my hand, but it's not until I push it further away that it detects it.

It is true. hand&Face default detection distance are different.
