### ISSUE TITLE
Hand detection distance

### ISSUE THREAD

**Issue by JERINPWILSON** [AlcheraInc/Face-Hand-Detection-Unity#8]
Guys the hands are not detected at a fairly near distance even if the whole palm is visible..it would be great if the hands are detected at even close proximity.

**Comment by camjam332** [comment]
You can get the detection working at a closer distance if you go into `HandService.cs` and make the `context.minHandSize` value larger. Have mine set to 120 and works well for me.

**Comment by JERINPWILSON** [comment]
Thanks for your reply.
